# Generated by Django 4.2.1 on 2023-05-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='id',
            new_name='sensor',
        ),
    ]
